[common]
env = "prod" # 可选值：dev、prod
enable_register = true
lang="zh-CN"
data_path = "data"
time_zone = "Asia/Shanghai"

[log]
file = "data/runtime.log"
level = "debug"
format = "console" # json、console

[web]
port = 8080
addr = "0.0.0.0"
domain = "http://localhost:8080"
ui_path = "data/webui"

[jwt]
jwt_key = "he-jwt-key"
jwt_secret = "123456abcdef"

[singlefile]
html_path = "data/html" # 为空默认在当前目录下创建html文件夹
max_version = 5
min_version_interval =  86400 # 两个版本之间的最小间隔时间
version_check_interval = 3600 # 检查版本间隔时间
version_check_limit = 100 # 检查版本数量限制
max_size = 20971520 # 20MB

[readability]
parser = "mozilla" # 解析器，目前只支持mozilla
exec_path = "/usr/lib/readability.js" # readability-parse脚本路径，为空会从系统环境变量PATH下查找

[zincsearch]
host = "http://localhost"
shared_num = 3
index_prefix = "history_engine_index"
user = "admin"
password = "admin"

[database]
drive = "mysql" #取值范围：mysql(tidb、mariadb)、sqlite3、postgres
db_path = "data/sqlite.db" # 仅sqlite数据库使用
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
name = "history"
ssl = "false"
charset = "utf8mb4"
timeout = "5s"

[redis]
addr = "127.0.0.1:6379"
password = ""
db = 0
