[common]
env = "prod" # 可选值：dev、prod
enable_register = true
lang="zh-CN"
data_path = "data"
time_zone = "Asia/Shanghai"
icon_path = "data/icon"
html_path = "data/html" # 为空默认在当前目录下创建html文件夹

[log]
file = "data/runtime.log"
level = "debug"
format = "console" # json、console

[web]
port = 8080
addr = "0.0.0.0"
domain = "http://localhost:8080"
ui_path = "data/webui"

[jwt]
jwt_key = "he-jwt-key"
jwt_secret = "123456abcdef"

[readability]
parser = "mozilla" # 解析器，目前只支持mozilla
exec_path = "/usr/lib/readability.js" # readability-parse脚本路径，为空会从系统环境变量PATH下查找

[search]
engine = "meili" # zinc、meili、es # es 暂未实现
prefix = "history_engine_index"

[zincsearch]
host = "http://localhost:4080"
shared_num = 3
user = "admin"
password = "admin"

[meilisearch]
host = "http://localhost:7070"
master_key = "" # https://www.meilisearch.com/docs/learn/configuration/instance_options#master-key

[elasticsearch]
host = ["http://localhost:9200"]
user = "elastic"
password = ""  # http basic auth
cloud_id = ""  # http basic auth
api_key = ""      # Base64-encoded token for authorization; if set, overrides username/password and service token.
server_token = "" # Service token for authorization; if set, overrides username/password.

[database]
drive = "mysql" #取值范围：mysql(tidb、mariadb)、sqlite3、postgres
db_path = "data/sqlite.db" # 仅sqlite数据库使用
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
name = "history"
ssl = "false"
charset = "utf8mb4"
timeout = "5s"
print_sql = false

[redis]
addr = "127.0.0.1:6379"
password = ""
db = 0
