// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"history-engine/engine/ent/icon"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Icon is the model entity for the Icon schema.
type Icon struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 域名
	Host string `json:"host,omitempty"`
	// 完整本地文件地址
	Path string `json:"path,omitempty"`
	// 入库时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 最后更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Icon) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case icon.FieldID:
			values[i] = new(sql.NullInt64)
		case icon.FieldHost, icon.FieldPath:
			values[i] = new(sql.NullString)
		case icon.FieldCreatedAt, icon.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Icon fields.
func (i *Icon) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case icon.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int64(value.Int64)
		case icon.FieldHost:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[j])
			} else if value.Valid {
				i.Host = value.String
			}
		case icon.FieldPath:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[j])
			} else if value.Valid {
				i.Path = value.String
			}
		case icon.FieldCreatedAt:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[j])
			} else if value.Valid {
				i.CreatedAt = value.Time
			}
		case icon.FieldUpdatedAt:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[j])
			} else if value.Valid {
				i.UpdatedAt = value.Time
			}
		default:
			i.selectValues.Set(columns[j], values[j])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Icon.
// This includes values selected through modifiers, order, etc.
func (i *Icon) Value(name string) (ent.Value, error) {
	return i.selectValues.Get(name)
}

// Update returns a builder for updating this Icon.
// Note that you need to call Icon.Unwrap() before calling this method if this Icon
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Icon) Update() *IconUpdateOne {
	return NewIconClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Icon entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Icon) Unwrap() *Icon {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Icon is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Icon) String() string {
	var builder strings.Builder
	builder.WriteString("Icon(")
	builder.WriteString(fmt.Sprintf("id=%v, ", i.ID))
	builder.WriteString("host=")
	builder.WriteString(i.Host)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(i.Path)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(i.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(i.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Icons is a parsable slice of Icon.
type Icons []*Icon
