// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FileType is the predicate function for filetype builders.
type FileType func(*sql.Selector)

// Host is the predicate function for host builders.
type Host func(*sql.Selector)

// Icon is the predicate function for icon builders.
type Icon func(*sql.Selector)

// Page is the predicate function for page builders.
type Page func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
